I18N = {
    "en-US": {
        "title": "Deus",
        "recording": "Recording...",
        "config": "Config",
        "key_explanation": "Specify one of the keys in the appropriate field. \n"
                           "If you use Yandex Speech API, then enter the string key \n"
                           "If you use Google Speech API, then select the path to the json file with the key \n",
        "openai_api_key": "OpenAI API Key",
        "speech_api_key": "Yandex Speech API Key",
        "speech_key_location": "Speech API Key Location (json file)",
        "speech_provider": "Speech provider",
        "threshold": "Microphone threshold",
        "language": "Language",
        "hide_buttons": "Hide buttons",
        "save": "Save",
        "cancel": "Cancel",
        "error": "Error",
        "openai_overload": "Currently OpenAI API is overloaded. Please try again later.",
        "openai_api_key_invalid": "OpenAI API Key is invalid. Please check it and try again.",
        "speech_api_key_invalid": "Speech API Key is invalid. Please check it and try again.",
        "threshold_invalid": "Threshold is invalid. Please check it and try again.",
        "you": "You",
        "deus": "Deus",
    },
    "ru-RU": {
        "title": "Деус",
        "recording": "Запись...",
        "config": "Настройки",
        "key_explanation": "Укажите один из ключей в нужном поле. \n"
                           "Если вы используете Yandex Speech API, то впишите строковый ключ \n"
                           "Если вы используете Google Speech API, то выберите путь к json файлу с ключом \n",
        "openai_api_key": "OpenAI API ключ",
        "speech_api_key": "Speech API ключ",
        "speech_key_location": "Google Speech API ключ (json файл)",
        "speech_provider": "Речевой провайдер",
        "threshold": "Чувствительность микрофона",
        "language": "Язык",
        "hide_buttons": "Скрыть кнопки",
        "save": "Сохранить",
        "cancel": "Отмена",
        "error": "Ошибка",
        "openai_overload": "Сейчас OpenAI API перегружен. Пожалуйста, попробуйте позже.",
        "openai_api_key_invalid": "OpenAI API Key неверный. Пожалуйста, проверьте его и попробуйте снова.",
        "speech_api_key_invalid": "Speech API Key неверный. Пожалуйста, проверьте его и попробуйте снова.",
        "threshold_invalid": "Порог неверный. Пожалуйста, проверьте его и попробуйте снова.",
        "you": "Вы",
        "deus": "Деус",
    },
    "he-IL": {
        "title": "דאוס",
        "recording": "הקלטה...",
        "config": "הגדרות",
        "key_explanation": "ציין אחד מהמפתחות בשדה המתאים. \n"
                           "אם אתה משתמש ב- Yandex Speech API, הכנס את המפתח המחרוזתי \n"
                           "אם אתה משתמש ב- Google Speech API, בחר את הנתיב לקובץ ה- json עם המפתח \n",
        "openai_api_key": "מפתח OpenAI API",
        "speech_api_key": "מפתח Speech API",
        "speech_key_location": "מיקום מפתח Speech API (קובץ json)",
        "speech_provider": "ספק דיבור",
        "threshold": "סף רמת קול",
        "language": "שפה",
        "hide_buttons": "הסתר כפתורים",
        "save": "שמור",
        "cancel": "בטל",
        "error": "שגיאה",
        "openai_overload": "OpenAI API כרגע מטען. אנא נסה שוב מאוחר יותר.",
        "openai_api_key_invalid": "מפתח OpenAI API לא תקין. אנא בדוק אותו ונסה שוב.",
        "speech_api_key_invalid": "מפתח Speech API לא תקין. אנא בדוק אותו ונסה שוב.",
        "threshold_invalid": "הסף לא תקין. אנא בדוק אותו ונסה שוב.",
        "you": "אתה",
        "deus": "דאוס",
    },
}
